export const NotificationsActionTypes = {
  GET_ALL_HEADER_REQUEST: 'notifications.GET_ALL_HEADER_REQUEST',
  GET_ALL_HEADER_SUCCESS: 'notifications.GET_ALL_HEADER_SUCCESS',
  GET_ALL_HEADER_ERROR: 'notifications.GET_ALL_HEADER_ERROR',
  GET_UNREAD_COUNT_REQUEST: 'notifications.GET_UNREAD_COUNT_REQUEST',
  GET_UNREAD_COUNT_SUCCESS: 'notifications.GET_UNREAD_COUNT_SUCCESS',
  GET_UNREAD_COUNT_ERROR: 'notifications.GET_UNREAD_COUNT_ERROR',
  MARK_AS_READ_REQUEST: 'notifications.MARK_AS_READ_REQUEST',
  MARK_AS_READ_SUCCESS: 'notifications.MARK_AS_READ_SUCCESS',
  MARK_AS_READ_ERROR: 'notifications.MARK_AS_READ_ERROR',
};
