export const SignalRActionTypes = {
  SET_SIGNALR_MESSAGE: 'staging.SET_SIGNALR_MESSAGE',
  SET_SIGNALR_MESSAGE_ERROR: 'staging.SET_SIGNALR_MESSAGE_ERROR',
  SET_SIGNALR_CONNECTIONS: 'staging.SET_SIGNALR_CONNECTIONS',
  SET_SIGNALR_CONNECTIONS_ERROR: 'staging.SET_SIGNALR_CONNECTIONS_ERROR',
};
