export const WPProcessStep2ActionTypes = {
  GET_JR_STEPS_DATA: 'workpaperProcess_step2.GET_JR_STEPS_DATA',
  GET_JR_STEPS_DATA_SUCCESS: 'workpaperProcess_step2.GET_JR_STEPS_DATA_SUCCESS',
  GET_JR_STEPS_DATA_ERROR: 'workpaperProcess_step2.GET_JR_STEPS_DATA_ERROR',

  APPROVE_JR: 'workpaperProcess_step2.APPROVE_JR',
  APPROVE_JR_SUCCESS: 'workpaperProcess_step2.APPROVE_JR_SUCCESS',
  APPROVE_JR_ERROR: 'workpaperProcess_step2.APPROVE_JR_ERROR',

  APPROVE_ALL_JR: 'workpaperProcess_step2.APPROVE_ALL_JR',
  APPROVE_ALL_JR_SUCCESS: 'workpaperProcess_step2.APPROVE_ALL_JR_SUCCESS',
  APPROVE_ALL_JR_ERROR: 'workpaperProcess_step2.APPROVE_ALL_JR_ERROR',

  GET_TRIFACTA_PARAMS: 'workpaperProcess_step2.GET_TRIFACTA_PARAMS',
  GET_TRIFACTA_PARAMS_SUCCESS: 'workpaperProcess_step2.GET_TRIFACTA_PARAMS_SUCCESS',
  GET_TRIFACTA_PARAMS_ERROR: 'workpaperProcess_step2.GET_TRIFACTA_PARAMS_ERROR',

  GET_TRIFACTA_JR_STEPS: 'workpaperProcess_step2.GET_TRIFACTA_JR_STEPS',
  GET_TRIFACTA_JR_STEPS_SUCCESS: 'workpaperProcess_step2.GET_TRIFACTA_JR_STEPS_SUCCESS',
  GET_TRIFACTA_JR_STEPS_ERROR: 'workpaperProcess_step2.GET_TRIFACTA_JR_STEPS_ERROR',

  SET_TRIFACTA_PARAMS: 'workpaperProcess_step2.SET_TRIFACTA_PARAMS',
  SET_TRIFACTA_PARAMS_SUCCESS: 'workpaperProcess_step2.SET_TRIFACTA_PARAMS_SUCCESS',
  SET_TRIFACTA_PARAMS_ERROR: 'workpaperProcess_step2.SET_TRIFACTA_PARAMS_ERROR',

  SET_TRIFACTA_JR_STEPS: 'workpaperProcess_step2.SET_TRIFACTA_JR_STEPS',
  SET_TRIFACTA_JR_STEPS_SUCCESS: 'workpaperProcess_step2.SET_TRIFACTA_JR_STEPS_SUCCESS',
  SET_TRIFACTA_JR_STEPS_ERROR: 'workpaperProcess_step2.SET_TRIFACTA_JR_STEPS_ERROR',

  PROCESS_WORKPAPER: 'workpaperProcess_step2.PROCESS_WORKPAPER',
  PROCESS_WORKPAPER_SUCCESS: 'workpaperProcess_step2.PROCESS_WORKPAPER_SUCCESS',
  PROCESS_TRIFACTAWORKPAPER_SUCCESS: 'workpaperProcess_step2.PROCESS_TRIFACTAWORKPAPER_SUCCESS',

  PROCESS_WORKPAPER_ERROR: 'workpaperProcess_step2.PROCESS_WORKPAPER_ERROR',

  EXPORT_DATA_FLOW: 'workpaperProcess_step2.EXPORT_DATA_FLOW',
  EXPORT_DATA_FLOW_SUCCESS: 'workpaperProcess_step2.EXPORT_DATA_FLOW_SUCCESS',
  EXPORT_DATA_FLOW_ERROR: 'workpaperProcess_step2.EXPORT_DATA_FLOW_ERROR',

  PROCESS_WORKPAPER_STATUS: 'workpaperProcess_step2.PROCESS_WORKPAPER_STATUS',
  PROCESS_WORKPAPER_STATUS_SUCCESS: 'workpaperProcess_step2.PROCESS_WORKPAPER_STATUS_SUCCESS',
  PROCESS_WORKPAPER_STATUS_SUCCESS_NO_TYPE: 'workpaperProcess_step2.PROCESS_WORKPAPER_STATUS_SUCCESS_NO_TYPE',
  PROCESS_TRIFACTAWORKPAPER_STATUS_SUCCESS: 'workpaperProcess_step2.PROCESS_TRIFACTAWORKPAPER_STATUS_SUCCESS',
  PROCESS_WORKPAPER_STATUS_ERROR: 'workpaperProcess_step2.PROCESS_WORKPAPER_STATUS_ERROR',
  PROCESS_WORKPAPER_STATUS_RESET: 'workpaperProcess_step2.PROCESS_WORKPAPER_STATUS_RESET',

  RESET: 'workpaperProcess_step2.RESET',

  PROCESS_IMPORT_FLOW: 'workpaperProcess_step2.PROCESS_IMPORT_FLOW',
  PROCESS_IMPORT_FLOW_SUCCESS: 'workpaperProcess_step2.PROCESS_IMPORT_FLOW_SUCCES',
  PROCESS_IMPORT_FLOW_ERROR: 'workpaperProcess_step2.PROCESS_IMPORT_FLOW_ERROR',
  PROCESS_IMPORT_FLOW_INITIATE_POLLING: 'workpaperProcess_step2.PROCESS_IMPORT_FLOW_INITIATE_POLLING',
  PROCESS_IMPORT_FLOW_INITIATE_POLLING_RESET: 'workpaperProcess_step2.PROCESS_IMPORT_FLOW_INITIATE_POLLING_RESET',

  GET_WORKPAPER_SETUP: 'workpaperProcess_step2.GET_WORKPAPER_SETUP',
  GET_WORKPAPER_SETUP_SUCCESS: 'workpaperProcess_step2.GET_WORKPAPER_SETUP_SUCCESS',
  GET_WORKPAPER_SETUP_ERROR: 'workpaperProcess_step2.GET_WORKPAPER_SETUP_ERROR',

  GET_WP_DMV_STATUS: 'workpaperProcess_step2.GET_WP_DMV_STATUS',
  GET_WP_DMV_STATUS_SUCCESS: 'workpaperProcess_step2.GET_WP_DMV_STATUS_SUCCESS',
  GET_WP_DMV_STATUS_ERROR: 'workpaperProcess_step2.GET_WP_DMV_STATUS_ERROR',

  SET_IS_DMT_STEP_COMPLETED: 'workpaperProcess_step2.SET_IS_DMT_STEP_COMPLETED',
  SET_IS_DMT_STEP_PARTIALLY_COMPLETED: 'workpaperProcess_step2.SET_IS_DMT_STEP_PARTIALLY_COMPLETED',
  SET_IS_DMT_STEP_SHOWN: 'workpaperProcess_step2.SET_IS_DMT_STEP_SHOWN',
  RESET_DMT_STEP: 'workpaperProcess_step2.RESET_DMT_STEP',

  AUTO_RUN_WORKPAPER_REQUEST: 'workpaperProcess_step2.AUTO_RUN_WORKPAPER_REQUEST',
  AUTO_RUN_WORKPAPER_SUCCESS: 'workpaperProcess_step2.AUTO_RUN_WORKPAPER_SUCCESS',
  AUTO_RUN_WORKPAPER_ERROR: 'workpaperProcess_step2.AUTO_RUN_WORKPAPER_ERROR',

  VALIDATE_DECRYPTION_FOR_WORKPAPER: 'workpaperProcess_step2.VALIDATE_DECRYPTION_FOR_WORKPAPER',
  VALIDATE_DECRYPTION_FOR_WORKPAPER_SUCCESS: 'workpaperProcess_step2.VALIDATE_DECRYPTION_FOR_WORKPAPER_SUCCESS',
  VALIDATE_DECRYPTION_FOR_WORKPAPER_ERROR: 'workpaperProcess_step2.VALIDATE_DECRYPTION_FOR_WORKPAPER_ERROR',
};
