/* eslint-disable sonarjs/no-duplicate-string */
export const datesFormats = {
  'zh-CN': { date: 'YYYY/M/D', time: 'H:mm:ss' },
  'fr-FR': { date: 'DD/MM/YYYY', time: 'HH:mm:ss' },
  'de-DE': { date: 'DD.MM.YYYY', time: 'HH:mm:ss' },
  'en-US': { date: 'M/D/YYYY', time: 'h:mm:ss A' },
  'af-ZA': { date: 'yyyy-MM-dd', time: 'hh:mm:ss' },
  'am-ET': { date: 'dd/MM/yyyy', time: 'hh:mm:ss A' },
  'ar-AE': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-BH': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-DZ': { date: 'dd-MM-yyyy', time: 'hh:mm:ss' },
  'ar-EG': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-IQ': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-JO': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-KW': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-LB': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-LY': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-MA': { date: 'dd-MM-yyyy', time: 'hh:mm:ss' },
  'ar-QA': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-SA': { date: 'dd/MM/yy', time: 'hh:mm:ss' },
  'ar-SY': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'ar-TN': { date: 'dd-MM-yyyy', time: 'hh:mm:ss' },
  'ar-YE': { date: 'dd/MM/yyyy', time: 'hh:mm:ss' },
  'as-IN': { date: 'dd-MM-yyyy', time: 'hh:mm:ss A' },
  'az-Cyrl-AZ': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'az-Latn-AZ': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'be-BY': { date: 'dd.MM.yy', time: 'hh:mm:ss A' },
  'bg-BG': { date: "d.M.yyyy 'r.'", time: 'HH:mm:ss ч' },
  'bn-BD': { date: 'd/M/yyyy', time: 'hh:mm:ss A' },
  'bn-IN': { date: 'dd-MM-yy', time: 'hh:mm:ss A' },
  'bo-CN': { date: 'yyyy/M/d', time: 'hh:mm:ss A' },
  'ca-ES': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'cs-CZ': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'cy-GB': { date: 'dd/MM/yyyy', time: 'hh:mm:ss A' },
  'da-DK': { date: 'dd-MM-yyyy', time: 'HH.mm.ss' },
  'de-AT': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'de-CH': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'de-LI': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'de-LU': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'el-GR': { date: 'd/M/yyyy', time: ',hh:mm:ss a' },
  'en-AU': { date: 'd/MM/yyyy', time: ',h:mm:ss A' },
  'en-BZ': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'en-CA': { date: 'yyyy-MM-dd', time: ',h:mm:ss A' },
  'en-GB': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'en-IE': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'en-IN': { date: 'dd-MM-yyyy', time: ',HH:mm:ss' },
  'en-JM': { date: 'd/M/yyyy', time: ',h:mm:ss a' },
  'en-NZ': { date: 'd/MM/yyyy', time: ',h:mm:ss a' },
  'en-PH': { date: 'dd/MM/yyyy', time: ',h:mm:ss a' },
  'en-SG': { date: 'd/M/yyyy', time: ',h:mm:ss a' },
  'en-TT': { date: 'dd/MM/yyyy', time: ',h:mm:ss a' },
  'en-ZA': { date: 'yyyy/MM/dd', time: ',HH:mm:ss' },
  'en-ZW': { date: 'd/M/yyyy', time: ',HH:mm:ss' },
  'es-AR': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-BO': { date: 'd/M/yyyy', time: ',HH:mm:ss' },
  'es-CL': { date: 'dd-MM-yyyy', time: 'H:mm:ss' },
  'es-CO': { date: 'd/MM/yyyy' },
  'es-CR': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-DO': { date: 'd/M/yyyy', time: 'h:mm:ss a' },
  'es-EC': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-ES': { date: 'dd/MM/yyyy', time: 'H:mm:ss' },
  'es-GT': { date: 'd/MM/yyyy', time: 'HH:mm:ss' },
  'es-HN': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-MX': { date: 'dd/MM/yyyy' },
  'es-NI': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-PA': { date: 'MM/dd/yyyy', time: 'h:mm:ss a' },
  'es-PE': { date: 'd/MM/yyyy', time: 'HH:mm:ss' },
  'es-PR': { date: 'MM/dd/yyyy', time: 'h:mm:ss a' },
  'es-PY': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-SV': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-US': { date: 'M/d/yyyy', time: 'h:mm:ss A' },
  'es-UY': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'es-VE': { date: 'd/M/yyyy', time: 'h:mm:ss a' },
  'et-EE': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'eu-ES': { date: 'yyyy/MM/dd', time: 'h:mm:ss a' },
  'fa-IR': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'fi-FI': { date: 'd.M.yyyy', time: 'HH.mm.ss' },
  'fil-PH': { date: 'M/d/yyyy', time: 'h:mm:ss A' },
  'fo-FO': { date: 'dd.MM.yyyy', time: 'h:mm:ss A' },
  'fr-BE': { date: 'dd-MM-yy', time: 'HH:mm:ss' },
  'fr-CA': { date: 'yyyy-MM-dd', time: ',HH:mm:ss' },
  'fr-CH': { date: 'dd.MM.yyyy', time: ',HH:mm:ss' },
  'fr-LU': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'fr-MC': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'ga-IE': { date: 'dd/MM/yyyy', time: ',h:mm:ss A' },
  'gl-ES': { date: 'dd/MM/yy', time: ',h:mm:ss A' },
  'gu-IN': { date: 'dd-MM-yy', time: ',h:mm:ss A' },
  'ha-Latn-NG': { date: 'd/M/yyyy', time: ',h:mm:ss A' },
  'he-IL': { date: 'dd/MM/yyyy', time: ',HH:mm:ss' },
  'hi-IN': { date: 'dd-MM-yyyy', time: ',h:mm:ss a' },
  'hr-HR': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'hu-HU': { date: 'yyyy. MM. dd.', time: 'HH:mm:ss' },
  'hy-AM': { date: 'dd.MM.yyyy', time: ',h:mm:ss A' },
  'id-ID': { date: 'dd/MM/yyyy', time: 'HH.mm.ss' },
  'ig-NG': { date: 'dd/MM/yyyy', time: 'h:mm:ss A' },
  'ii-CN': { date: 'yyyy/M/d', time: 'h:mm:ss A' },
  'is-IS': { date: 'd.M.yyyy', time: 'h:mm:ss A' },
  'it-CH': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'it-IT': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'ja-JP': { date: 'yyyy/MM/dd', time: 'HH:mm:ss' },
  'kk-KZ': { date: 'dd.MM.yyyy', time: 'HH:mm:ss A' },
  'kl-GL': { date: 'dd-MM-yyyy', time: 'h:mm:ss A' },
  'km-KH': { date: 'dd/MM/yy', time: 'h:mm:ss A' },
  'kn-IN': { date: 'dd-MM-yy', time: 'h:mm:ss' },
  'ko-KR': { date: 'yyyy-MM-dd' },
  'kok-IN': { date: 'dd-MM-yyyy', time: 'h:mm:ss A' },
  'lt-LT': { date: 'yyyy-MM-dd', time: 'HH:mm:ss' },
  'lv-LV': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'mk-MK': { date: 'dd.M.yyyy', time: 'h:mm:ss A' },
  'ml-IN': { date: 'd/M/yyyy', time: 'h:mm:ss A' },
  'mr-IN': { date: 'dd-MM-yyyy', time: 'h:mm:ss A' },
  'ms-BN': { date: 'd/MM/yyyy', time: 'h:mm:ss' },
  'ms-MY': { date: 'd/MM/yyyy', time: 'h:mm:ss' },
  'mt-MT': { date: 'dd/MM/yyyy', time: 'h:mm:ss A' },
  'nb-NO': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'ne-NP': { date: 'M/d/yyyy', time: 'h:mm:ss A' },
  'nl-BE': { date: 'd/MM/yyyy', time: 'HH:mm:ss' },
  'nl-NL': { date: 'd-M-yyyy', time: 'HH:mm:ss' },
  'nn-NO': { date: 'dd.MM.yyyy', time: 'h:mm:ss A' },
  'or-IN': { date: 'dd-MM-yy', time: 'h:mm:ss A' },
  'pl-PL': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'ps-AF': { date: 'yyyy/M/d', time: 'h:mm:ss A' },
  'pt-BR': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'pt-PT': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'rm-CH': { date: 'dd-MM-yyyy', time: 'h:mm:ss A' },
  'ro-RO': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'ru-RU': { date: 'dd.MM.yyyy', time: 'HH:mm:ss' },
  'rw-RW': { date: 'yyyy-MM-dd', time: 'h:mm:ss A' },
  'si-LK': { date: 'yyyy-MM-dd', time: 'h:mm:ss A' },
  'sk-SK': { date: 'd. M. yyyy', time: 'HH:mm:ss' },
  'sl-SI': { date: 'd. MM. yyyy', time: 'HH:mm:ss' },
  'sq-AL': { date: 'd.M.yyyy', time: 'h:mm:ss A' },
  'sr-Cyrl-BA': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'sr-Cyrl-ME': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'sr-Cyrl-RS': { date: 'dd.MM.yyyy.', time: 'HH:mm:ss' },
  'sr-Latn-CS': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'sr-Latn-ME': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'sr-Latn-RS': { date: 'd.M.yyyy.', time: 'HH:mm:ss' },
  'sv-FI': { date: 'dd-MM-yyyy', time: 'HH:mm:ss' },
  'sv-SE': { date: 'yyyy-MM-dd', time: 'HH:mm:ss' },
  'sw-KE': { date: 'M/d/yyyy', time: 'HH:mm:ss' },
  'ta-IN': { date: 'dd-MM-yyyy', time: 'h:mm:ss' },
  'te-IN': { date: 'dd-MM-yy', time: 'h:mm:ss A' },
  'th-TH': { date: 'd/M/yyyy', time: 'HH:mm:ss' },
  'tr-TR': { date: 'd.MM.yyyy', time: 'HH:mm:ss' },
  'ur-PK': { date: 'dd/MM/yyyy', time: 'h:mm:ss A' },
  'vi-VN': { date: 'dd/MM/yyyy', time: 'HH:mm:ss' },
  'yo-NG': { date: 'dd/MM/yyyy', time: 'h:mm:ss A' },
  'zh-TW': { date: 'yyyy/M/d' },
  'zh-SG': { date: 'd/M/yyyy' },
};

export const localeLanguages = [
  { value: 'en-US', text: 'English (United States)' },
  { value: 'de-DE', text: 'Deutsch (Deutschland)' },
  { value: 'fr-FR', text: 'français (France)' },
  { value: 'zh-CN', text: '中文(中华人民共和国)' },
  { value: 'es-US', text: 'Spanish (United States)' },
  { value: 'pt-BR', text: 'Portuguese (Brazil)' },
  { value: 'fr-CA', text: 'French (Canada)' },
  { value: 'ja-JP', text: 'Japanese (Japan)' },
  { value: 'sl-SI', text: 'Slovenian (Slovenia)' },
  { value: 'ko-KR', text: 'Korean (Korea)' },
  { value: 'hr-HR', text: 'Croatian (Croatia)' },
  { value: 'sr-RS', text: 'Serbian (Serbia)' },
  { value: 'af-ZA', text: 'Afrikaans (South Africa)' },
  { value: 'am-ET', text: 'Amharic (Ethiopia)' },
  { value: 'ar-AE', text: 'Arabic (United Arab Emirates)' },
  { value: 'ar-BH', text: 'Arabic (Bahrain)' },
  { value: 'ar-DZ', text: 'Arabic (Algeria)' },
  { value: 'ar-EG', text: 'Arabic (Egypt)' },
  { value: 'ar-IQ', text: 'Arabic (Iraq)' },
  { value: 'ar-JO', text: 'Arabic (Jordan)' },
  { value: 'ar-KW', text: 'Arabic (Kuwait)' },
  { value: 'ar-LB', text: 'Arabic (Lebanon)' },
  { value: 'ar-LY', text: 'Arabic (Libya)' },
  { value: 'ar-MA', text: 'Arabic (Morocco)' },
  { value: 'ar-QA', text: 'Arabic (Oman)' },
  { value: 'ar-SA', text: 'Arabic (Saudi Arabia)' },
  { value: 'ar-SY', text: 'Arabic (Syria)' },
  { value: 'ar-TN', text: 'Arabic (Tunisia)' },
  { value: 'ar-YE', text: 'Arabic (Yemen)' },
  { value: 'as-IN', text: 'Assamese (India)' },
  { value: 'az-Cyrl-AZ', text: 'Azerbaijani (Cyrillic, Azerbaijan)' },
  { value: 'az-Latn-AZ', text: 'Azerbaijani (Latin, Azerbaijan)' },
  { value: 'be-BY', text: 'Belarusian (Belarus)' },
  { value: 'bg-BG', text: 'Bulgarian (Bulgaria)' },
  { value: 'bn-BD', text: 'Bangla (Bangladesh)' },
  { value: 'bn-IN', text: 'Bengali (India)' },
  { value: 'bo-CN', text: 'Tibetan (China)' },
  { value: 'ca-ES', text: 'Catalan (Spain)' },
  { value: 'cs-CZ', text: 'Czech (Czech Republic)' },
  { value: 'cy-GB', text: 'Welsh (United Kingdom)' },
  { value: 'da-DK', text: 'Danish (Denmark)' },
  { value: 'de-AT', text: 'German (Austria)' },
  { value: 'de-CH', text: 'German (Switzerland)' },
  { value: 'de-LI', text: 'German (Liechtenstein)' },
  { value: 'de-LU', text: 'German (Luxembourg)' },
  { value: 'el-GR', text: 'Greek (Greece)' },
  { value: 'en-AU', text: 'English (Australia)' },
  { value: 'en-BZ', text: 'English (Belize)' },
  { value: 'en-CA', text: 'English (Canada)' },
  { value: 'en-GB', text: 'English (United Kingdom)' },
  { value: 'en-IE', text: 'English (Ireland)' },
  { value: 'en-IN', text: 'English (India)' },
  { value: 'en-JM', text: 'English (Jamaica)' },
  { value: 'en-NZ', text: 'English (New Zealand)' },
  { value: 'en-PH', text: 'English (Philippines)' },
  { value: 'en-SG', text: 'English (Singapore)' },
  { value: 'en-TT', text: 'English (Trinidad and Tobago)' },
  { value: 'en-ZA', text: 'English (South Africa)' },
  { value: 'en-ZW', text: 'English (Zimbabwe)' },
  { value: 'es-AR', text: 'Spanish (Argentina)' },
  { value: 'es-BO', text: 'Spanish (Bolivia)' },
  { value: 'es-CL', text: 'Spanish (Chile)' },
  { value: 'es-CO', text: 'Spanish (Colombia)' },
  { value: 'es-CR', text: 'Spanish (Costa Rica)' },
  { value: 'es-DO', text: 'Spanish (Dominican Republic)' },
  { value: 'es-EC', text: 'Spanish (Ecuador)' },
  { value: 'es-ES', text: 'Spanish (Spain)' },
  { value: 'es-GT', text: 'Spanish (Guatemala)' },
  { value: 'es-HN', text: 'Spanish (Honduras)' },
  { value: 'es-MX', text: 'Spanish (Mexico)' },
  { value: 'es-NI', text: 'Spanish (Nicaragua)' },
  { value: 'es-PA', text: 'Spanish (Panama)' },
  { value: 'es-PE', text: 'Spanish (Peru)' },
  { value: 'es-PR', text: 'Spanish (Puerto Rico)' },
  { value: 'es-PY', text: 'Spanish (Paraguay)' },
  { value: 'es-SV', text: 'Spanish (El Salvador)' },
  { value: 'es-UY', text: 'Spanish (Uruguay)' },
  { value: 'es-VE', text: 'Spanish (Venezuela)' },
  { value: 'et-EE', text: 'Estonian (Estonia)' },
  { value: 'eu-ES', text: 'Basque (Spain)' },
  { value: 'fa-IR', text: 'Persian (Iran)' },
  { value: 'fi-FI', text: 'Finnish (Finland)' },
  { value: 'fil-PH', text: 'Filipino (Philippines)' },
  { value: 'fo-FO', text: 'Faroese (Faroe Islands)' },
  { value: 'fr-BE', text: 'French (Belgium)' },
  { value: 'fr-CH', text: 'French (Switzerland)' },
  { value: 'fr-LU', text: 'French (Luxembourg)' },
  { value: 'fr-MC', text: 'French (Monaco)' },
  { value: 'ga-IE', text: 'Irish (Ireland)' },
  { value: 'gl-ES', text: 'Galician (Galician)' },
  { value: 'gu-IN', text: 'Gujarati (India)' },
  { value: 'ha-Latn-NG', text: 'Hausa (Latin, Nigeria)' },
  { value: 'he-IL', text: 'Hebrew (Israel)' },
  { value: 'hi-IN', text: 'Hindi (India)' },
  { value: 'hu-HU', text: 'Hungarian (Hungary)' },
  { value: 'hy-AM', text: 'Armenian (Armenia)' },
  { value: 'id-ID', text: 'Indonesian (Indonesia)' },
  { value: 'ig-NG', text: 'Igbo (Nigeria)' },
  { value: 'ii-CN', text: 'Sichuan Yi (China)' },
  { value: 'is-IS', text: 'Icelandic (Iceland)' },
  { value: 'it-CH', text: 'Italian (Switzerland)' },
  { value: 'it-IT', text: 'Italian (Italy)' },
  { value: 'kl-GL', text: 'Kalaallisut (Greenland)' },
  { value: 'km-KH', text: 'Khmer (Cambodia)' },
  { value: 'kn-IN', text: 'Kannada (India)' },
  { value: 'kok-IN', text: 'Konkani (India)' },
  { value: 'lt-LT', text: 'Lithuanian (Lithuania)' },
  { value: 'lv-LV', text: 'Latvian (Latvia)' },
  { value: 'mk-MK', text: 'Macedonian (Macedonia)' },
  { value: 'ml-IN', text: 'Malayalam (India)' },
  { value: 'mr-IN', text: 'Marathi (India)' },
  { value: 'ms-BN', text: 'Malay (Brunei)' },
  { value: 'ms-MY', text: 'Malay (Malaysia)' },
  { value: 'mt-MT', text: 'Maltese (Malta)' },
  { value: 'nb-NO', text: 'Norwegian Bokmål (Norway)' },
  { value: 'ne-NP', text: 'Nepali (Nepal)' },
  { value: 'nl-BE', text: 'Dutch (Belgium)' },
  { value: 'nl-NL', text: 'Dutch (Netherlands)' },
  { value: 'nn-NO', text: 'Norwegian Nynorsk (Norway)' },
  { value: 'or-IN', text: 'Oriya (India)' },
  { value: 'pl-PL', text: 'Polish (Poland)' },
  { value: 'ps-AF', text: 'Pashto (Afghanistan)' },
  { value: 'pt-PT', text: 'Portuguese (Portugal)' },
  { value: 'rm-CH', text: 'Romansh (Switzerland)' },
  { value: 'ro-RO', text: 'Romanian (Romania)' },
  { value: 'ru-RU', text: 'Russian (Russia)' },
  { value: 'rw-RW', text: 'Kinyarwanda (Rwanda)' },
  { value: 'si-LK', text: 'Sinhala (Sri Lanka)' },
  { value: 'sk-SK', text: 'Slovak (Slovakia)' },
  { value: 'sq-AL', text: 'Albanian (Albania)' },
  { value: 'sr-Cyrl-BA', text: 'Serbian (Cyrillic, Bosnia and Herzegovina)' },
  { value: 'sr-Cyrl-ME', text: 'Serbian (Cyrillic, Montenegro)' },
  { value: 'sr-Cyrl-RS', text: 'Serbian (Cyrillic, Serbia)' },
  { value: 'sr-Latn-CS', text: 'Serbian (Latin, Bosnia and Herzegovina)' },
  { value: 'sr-Latn-ME', text: 'Serbian (Latin, Montenegro)' },
  { value: 'sr-Latn-RS', text: 'Serbian (Latin, Serbia)' },
  { value: 'sv-FI', text: 'Swedish (Finland)' },
  { value: 'sv-SE', text: 'Swedish (Sweden)' },
  { value: 'sw-KE', text: 'Swahili (Kenya)' },
  { value: 'ta-IN', text: 'Tamil (India)' },
  { value: 'te-IN', text: 'Telugu (India)' },
  { value: 'th-TH', text: 'Thai (Thailand)' },
  { value: 'tr-TR', text: 'Turkish (Turkey)' },
  { value: 'ur-PK', text: 'Urdu (Pakistan)' },
  { value: 'vi-VN', text: 'Vietnamese (Vietnam)' },
  { value: 'yo-NG', text: 'Yoruba (Nigeria)' },
  { value: 'zh-TW', text: 'Chinese (Traditional)' },
  { value: 'zh-SG', text: 'Chinese (Singapore)' },
];
