export const Actions = {
  VIEW: 'view',
  UPDATE: 'update',
  DELETE: 'delete',
  ADD: 'add',
  APPROVE: 'approve',
  SUBMIT: 'submit',
};

export const Permissions = {
  APP_SETUP_ROLE_USERS: 'appSetupRoleUsers',
  BLACKOUT_SCHEDULE: 'blackoutSchedule',
  CLIENT: 'client',
  CLIENT_APPLICATION_MAPPING: 'clientApplicationMapping',
  CLIENT_COMPONENT_MAPPING: 'clientComponentMapping',
  CLIENT_EXTERNAL_ACKNOWLEDGE: 'client_External_Acknowledge',
  CLIENT_EXTERNAL_OUTPUTS: 'client_External_Outputs',
  CLIENT_RECERTIFY: 'client_Recertify',
  CLIENT_STAGING_STORAGE: 'clientStagingStorage',
  CONTENT_LIBRARY_PIPELINES: 'content_Library_Pipelines',
  CONNECTIONS: 'connections',
  CONNECTOR_TEMPLATES: 'connectorTemplates',
  DATA_MODALS: 'dataModels',
  DATA_PIPELINE: 'dataPipeline',
  DATA_REQUESTS: 'dataRequests',
  DATA_REQUESTS_OUTGOING: 'dataRequests_Outgoing',
  DATA_REQUESTS_EXTERNAL: 'dataRequests_External',
  DATA_REQUESTS_INTERNAL: 'dataRequests_Internal',
  DATA_REQUESTS_TRANSFER: 'dataRequests_Transfer',
  DATA_SOURCES: 'dataSources',
  DATA_SOURCE_SUBSCRIPTION: 'dataSourceSubscription',
  DATA_SOURCE_WORKFLOW: 'dataSourceWorkflow',
  DELOITTE_CLIENT_ROLE_USERS: 'deloitteClientRoleUsers',
  DELOITTE_ENGAGEMENT_ROLE_USERS: 'deloitteEngagementRoleUsers',
  ENGAGEMENT_CLOSEOUT: 'engagementCloseout',
  ENGAGEMENTS: 'engagements',
  ENGAGEMENT_EXTERNAL_ACKNOWLEDGE: 'engagement_External_Acknowledge',
  ENGAGEMENT_RECERTIFY: 'engagement_Recertify',
  ENGAGEMENT_WORKPAPERS: 'engagementWorkpapers',
  ENTITIES: 'entities',
  EXTERNAL_USER_DOMAIN_WHITELIST: 'externalUserDomainWhiteList',
  EXTRACTION_BUNDLES: 'extractionBundles',
  EXTERNAL_CLIENT_ROLE_USERS: 'externalClientRoleUsers',
  EXTERNAL_ENGAGEMENT_ROLE_USERS: 'externalEngagementRoleUsers',
  LEGAL_HOLD: 'legalHold',
  ORGS: 'orgs',
  RATIONALE: 'rationale',
  RELEASES: 'releases',
  RETENTION_PERIOD: 'retentionPeriod',
  REVIEW_NOTES: 'reviewNotes',
  SECURE_AGENT: 'secureAgent',
  SOURCE_SYSTEMS: 'sourceSystems',
  STAGING_FOLDER_STRUCTURE: 'stagingFolderStructure',
  SUBORGS: 'suborgs',
  TAGS: 'tags',
  TICKMARKS: 'tickmarks',
  WORK_ITEMS: 'workItems',
  ENGAGEMENT_WORKPAPER_REVIEW: 'engagementWorkpaperReview',
  ROLES: 'roles',
  APP_RECERTIFY: 'app_Recertify',
  CUSTOM_TRIFACTA_WORKPAPER: 'customTrifactaWorkpaper',
  REPLACE_DATA_MODEL: 'replace_Data_Model',
};

export const PagePermissions = {
  ADMIN_MAINTENANCE: 'admin_Maintenance',
  ADMIN_NOTIFICATIONS: 'admin_Notifications',
  ADMIN_ROLE_MANAGEMENT: 'admin_RoleManagement',
  ADMIN_REPORT: 'admin_Report',
  ADMIN_SEGREGATION_OF_DUTIES: 'admin_SegregationOfDuties',
  ADMIN_USERS: 'admin_Users',
  CLIENT_SETUP_LIST: 'clientSetup_List',
  CLIENT_SETUP_SETUP: 'clientSetup_Setup',
  CLIENT_SETUP_SETUP_APPLICATION_MAPPING: 'clientSetup_SetupApplicationMapping',
  CLIENT_SETUP_SETUP_COMPONENT_MAPPING: 'clientSetup_SetupComponentMapping',
  CLIENT_SETUP_SETUP_CONNECTIONS: 'clientSetup_SetupConnections',
  CLIENT_SETUP_SETUP_DATA_SOURCES: 'clientSetup_SetupDataSources',
  CLIENT_SETUP_SETUP_DETAILS: 'clientSetup_SetupDetails',
  CLIENT_SETUP_SETUP_ENGAGEMENTS: 'clientSetup_SetupEngagements',
  CLIENT_SETUP_SETUP_ENTITIES: 'clientSetup_SetupEntities',
  CLIENT_SETUP_SETUP_INFORMATICA: 'clientSetup_SetupInformatica',
  CLIENT_SETUP_STAGING: 'clientSetup_Staging',
  CLIENT_SETUP_USERS: 'clientSetup_Users',
  CLIENT_VIEW_SETUP: 'clientView_Setup',
  CLIENT_VIEW_SETUP_BLACKOUT: 'clientView_SetupBlackout',
  CLIENT_VIEW_SETUP_DATA_SOURCES: 'clientView_SetupDataSources',
  CLIENT_VIEW_SETUP_SECURE_AGENT: 'clientView_SetupSecureAgent',
  CLIENT_VIEW_USERS: 'clientView_Users',
  CONTENT_LIBRARY_BUNDLES: 'contentLibrary_Bundles',
  CONTENT_LIBRARY_CONNECTOR_TEMPLATES: 'contentLibrary_ConnectorTemplates',
  CONTENT_LIBRARY_DATA_MODELS: 'contentLibrary_DataModels',
  CONTENT_LIBRARY_PIPELINES: 'contentLibrary_Pipelines',
  CONTENT_LIBRARY_DATA_MODELS_DATA_MODEL_VALIDATIONS: 'contentLibrary_DataModels_DataModelValidations',
  CONTENT_LIBRARY_GLOSSARY: 'contentLibrary_Glossary',
  CONTENT_LIBRARY_RELEASES: 'contentLibrary_Releases',
  CONTENT_LIBRARY_RELEASES_BUNDLES: 'contentLibrary_Releases_Bundles',
  CONTENT_LIBRARY_RELEASES_CONNECTOR_TEMPLATES: 'contentLibrary_Releases_ConnectorTemplates',
  CONTENT_LIBRARY_RELEASES_DATA_MODELS: 'contentLibrary_Releases_DataModels',
  CONTENT_LIBRARY_RELEASES_GLOSSARY: 'contentLibrary_Releases_Glossary',
  CONTENT_LIBRARY_RELEASES_SOURCE_SYSTEMS: 'contentLibrary_Releases_SourceSystems',
  CONTENT_LIBRARY_RELEASES_TAGS: 'contentLibrary_Releases_Tags',
  CONTENT_LIBRARY_RELEASES_WORKPAPERS: 'contentLibrary_Releases_Workpapers',
  CONTENT_LIBRARY_SOURCE_SYSTEMS: 'contentLibrary_SourceSystems',
  CONTENT_LIBRARY_TAGS: 'contentLibrary_Tags',
  CONTENT_LIBRARY_WORKPAPERS: 'contentLibrary_Workpapers',
  ENGAGEMENT_CLOSEOUT: 'engagement_Closeout',
  ENGAGEMENT_CONFIGURE_APPROVAL_WORKFLOW: 'engagement_ConfigureApprovalWorkflow',
  ENGAGEMENT_DATA_PIPELINE: 'engagement_DataPipeline',
  ENGAGEMENT_DATA_REQUEST: 'engagement_DataRequest',
  ENGAGEMENT_DATA_REQUEST_DASHBOARD: 'engagement_DataRequestDashboard',
  ENGAGEMENT_DATA_REQUEST_OUTGOING: 'engagement_DataRequestOutgoing',
  ENGAGEMENT_ENGAGEMENT_DASHBOARD: 'engagement_EngagementDashboard',
  ENGAGEMENT_LEGAL_HOLD: 'engagement_LegalHold',
  ENGAGEMENT_STAGING: 'engagement_Staging',
  ENGAGEMENT_SUBSCRIBE_TO_DATA_SOURCES: 'engagement_SubscribeToDataSources',
  ENGAGEMENT_USERS_DASHBOARD: 'engagement_UsersDashboard',
  ENGAGEMENT_WORK_ITEMS_DASHBOARD: 'engagement_WorkItemsDashboard',
  ADMIN: 'admin',
  CLIENT_SETUP: 'clientSetup',
  CLIENT_VIEW: 'clientView',
  CONTENT_LIBRARY: 'contentLibrary',
  ENGAGEMENT: 'engagement',
};

export const checkPermissions = (permissions, permission, action) => {
  return permission && permissions[permission] && permissions[permission][action];
};
