export const WORKPAPER_TYPES = Object.freeze({
  TRIFACTA: 'Trifacta',
  CORTEX: 'Cortex',
  NOTEBOOK: 'Notebook',
});

export const WORKPAPER_CANVAS_TYPES = Object.freeze({
  TRIFACTA_CL_CANVAS: 'TRIFACTA_CL_CANVAS',
  TRIFACTA_DMT_CANVAS: 'TRIFACTA_DMT_CANVAS',
  TRIFACTA_BUNDLE_TRANSFORMATION_CANVAS: 'TRIFACTA_BUNDLE_TRANSFORMATION_CANVAS',
  TRIFACTA_ENGAGEMENT_CANVAS: 'TRIFACTA_ENGAGEMENT_CANVAS',
  TRIFACTA_ENGAGEMENT_WIZARD: 'TRIFACTA_ENGAGEMENT_WIZARD',
  CORTEX_ENGAGEMENT_WIZARD: 'CORTEX_ENGAGEMENT_WIZARD',
  NOTEBOOKS_CANVAS: 'NOTEBOOKS_CANVAS',
});
