export const DATA_REQUEST_STATUS = {
  APPROVED_AND_SCHEDULED: 'ApprovedAndScheduled',
  CHANGE_SCHEDULE_PARAMETERS: 'ChangeScheduleParameters',
  DRAFT: 'Draft',
  EXTRACTION_COMPLETE: 'ExtractionComplete',
  EXTRACTION_FAILED: 'ExtractionFailed',
  EXTRACTION_IN_PROGRESS: 'ExtractionInProgress',
  READY_FOR_EXTRACTION: 'ReadyForExtraction',
  READY_FOR_TRANSFER: 'ReadyForTransfer',
  REJECTED_BY_AUDITOR: 'RejectedByAuditor',
  REJECTED_BY_CLIENT: 'RejectedByClient',
  RESCHEDULE_REQUESTED: 'RescheduleRequested',
  TRANSFER_COMPLETE: 'TransferComplete',
  TRANSFER_FAILED: 'TransferFailed',
  TRANSFER_IN_PROGRESS: 'TransferInProgress',
  TRANSFER_REJECTED: 'TransferRejected',
  WAITING_FOR_AUDITOR_APPROVAL: 'WaitingForAuditorApproval',
  WAITING_FOR_CLIENT_EXTRACTIONS_APPROVAL: 'WaitingForClientExtractionApproval',
  WAITING_FOR_CLIENT_TRANSFER_APPROVAL: 'WaitingForClientTransferApproval',
  NOT_SUBMITTED: '',
  CONSOLIDATING_RAW_FILES: 'ConsolidatingRawFiles',
  ERROR_CONSOLIDATING_RAW_FILES: 'Error_ConsolidatingRawFiles',
  IS_DONE: 'IsDone',
};
