export const CLCDMActionTypes = {
  FETCH_CDMS_LIST: 'CLDataModels.FETCH_CDMS_LIST',
  FETCH_CDMS_LIST_SUCCESS: 'CLDataModels.FETCH_CDMS_LIST_SUCCESS',
  FETCH_CDMS_LIST_ERROR: 'CLDataModels.FETCH_CDMS_LIST_ERROR',
  UPDATE_CDM_REQUEST: 'CLDataModels.UPDATE_CDM_REQUEST',
  UPDATE_CDM_SUCCESS: 'CLDataModels.UPDATE_CDM_SUCCESS',
  UPDATE_CDM_ERROR: 'CLDataModels.UPDATE_CDM_ERROR',
  DELETE_CDM_REQUEST: 'CLDataModels.DELETE_CDM_REQUEST',
  DELETE_CDM_SUCCESS: 'CLDataModels.DELETE_CDM_SUCCESS',
  DELETE_CDM_ERROR: 'CLDataModels.DELETE_CDM_ERROR',
  GET_MAPPED_DMS_OF_CDM: 'CLDataModels.GET_MAPPED_DMS_OF_CDM',
  GET_MAPPED_DMS_OF_CDM_SUCCESS: 'CLDataModels.GET_MAPPED_DMS_OF_CDM_SUCCESS',
  GET_MAPPED_DMS_OF_CDM_ERROR: 'CLDataModels.GET_MAPPED_DMS_OF_CDM_ERROR',
};
